// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image6":return img`
..................................
..................................
.........fffff....................
........ffcccf....................
......fffe494fffff................
......fcce494ffccff...............
......fcce494ec4dcf...............
.....ffc4e494ee4deff..............
.....fc44e494ee4ddcf..............
.....fc44eeee4e4ddcf..............
.....fc4eee444e4dd4f..............
.....fc4e4e4444e4d4f..............
.....fc4e4b444444d4ff.............
.....fc4e4644444444cff............
.....fecee444f44eee4eff...........
.....ffcee444444ec.e4ef...........
.....fcefeee44eeec.ee4ff..........
....ffeeefeeee44ec.eedcff.........
...ffc4eefeeee44ec.eeddef.........
..ffc444cffce444ee.eeddef.........
..fc4444cffeceeeee.cdddef.........
.ffe444eefffceecf..fddddf.........
.ff4444eeffecccec..fdd64f.........
.ffee44cfffceeeede.cdd64f.........
.ffee4effffeeeebdee4ddddf.........
.ffeecffffc4eeebdee44dddf.........
.ffeeff.fee4eee4dce4e44ef.........
.ffefff.fee4eeed4cece4eef.........
.fffff.ffcee4edd4cffe4fff.........
.ffff..fceee4bd4e4cfeeff..........
......ffeec4eddef4effff...........
......feecfffffffe4cff............
.....ffceeef....fc4eef............
.....fce4ecf....fed4ef............
.....fce4ecff...fed4eff...........
.....fce4eeef...fe4d4cf...........
.....fce44eef...fe4d4cf...........
.....fcee4eef...fe4d4ef...........
.....fcee4eff...fc4d4ef...........
.....fcee4ef....fc4dd4f...........
.....fcccecf....fceeeef...........
.....fffffff....fffffff...........
..................................
..................................
..................................
..................................
..................................
`;
            case "image7":return img`
..................1111.................
.................11ee11................
.............111.14444111..............
.............1c11142221c1111...........
............11e21f4444feecf1...........
............1ee22ece44fceef1...........
............1e2222eccccceec1...........
..........111cebbeebe2eeeec1...........
..........1cceee22e2bbeeeec11.111......
...1111111122ecccebbe2ceccec111c1......
...1ccccccceeeccffeebb2efcee1cec111111.
..1122cee222ccfffffceeceffcceee1ee1ec1.
.11e22cccec8fcffffffb22eff1cce1eceeee11
112222222288ccffffe22ebcee111ceee44eef1
1e2d111442cfcfffff22e2ccce11cee442244e1
1edd444d1d22cfffff22ee2ccec1ee2ec..c4e1
1e14...24132effff22beecccecce2..e..24e1
1ed2cc.c.4ddeffffbe2eeccfcfe2c...ce44c1
111422c..c41efffff22eeccff1e2ec2e224b11
..1144222221efffff2eeeccf111142224dc11.
...1cb44224dcfffffceecccf111d1dddb111..
...111c444c1ffffffceeccc1111ceecc11....
.....11111111ffffceeccc11..1111111.....
......111...1111fceeec11...............
..............1f11eec11................
..............1111cee1.................
................11eec1.................
................1ceec1.................
................1fecc1.................
................11e111.................
.................111...................
`;
            case "image3":return img`
..................
..................
..................
..................
..................
..................
.......d111..e....
.......df1f..9e...
.......d111..9e...
........d1...9.e..
.....d1ddddd.9.e..
....d1.d111.191e1.
....d1..d1..19111.
....d1.d111..9.e..
....d1..d1...9.e..
.......d111..9e...
.......d1d1..9e...
.......d1d1..e....
.......d1d1.......
.......d1d1.......
..................
..................
..................
..................
..................
..................
..................
..................
`;
            case "image4":return img`
.........................
.........................
.........................
..........cbb............
.........cbbbb...........
.........cb9b9...........
.........cb9b9.cb........
.........cbbbb.69........
..........cbb..cb........
.........ccbbb.cb........
......cbbbcb9bcbb........
......cb.ccb9b...........
......69.ccbbb...........
......cb.ccbbb...........
..........cbbb...........
..........cbcb...........
..........cbcb...........
..........cbcb...........
..........cbcb...........
..........cbcb...........
..........cbcb...........
.........................
.........................
.........................
.........................
`;
            case "image8":return img`
. . . . . . . . . . . . . . . . . . 
1 b . . . . . . . . . . . . b 1 . . 
1 b b . . . . . . . . . . b b 1 . . 
1 b b . . . c b b b b . . b b 1 . . 
1 b b . . c c b b b b . . b b 1 . . 
. . e . . c d f c b f . . e . . . . 
. . e . . c d f c b f . . e . . . . 
. . d d c c c 4 4 4 4 c d d . . . . 
. . e . . c c 4 d d 4 . . e . . . . 
. . e . . c c 4 4 4 4 . . e . . . . 
. . . . . c b 4 4 4 b . . . . . . . 
. . . . . c b 4 . c b . . . . . . . 
. . . . . c b . . c b . . . . . . . 
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
`;
            case "image9":return img`
.........................
.........................
...................b.....
...........cbbb....b.....
..........ccbbbb...b.....
..........ccffff...b.....
..........ccbbfb...b.....
..........ccbbfb...b.....
..........cccbfb...b.....
......bb11cccccc...b.....
......bfc1ccbbbb...b.....
......bfc1ccbbbbc.ccc....
......bfc1ccbbbbcbbf.....
......bfc1ffffff...b.....
......bfc1bccccb.........
......bfc1bc..cb.........
......bfc1f....f.........
......bfc1b....b.........
......bfc1c....c.........
......bb11c....c.........
.........................
.........................
.........................
.........................
.........................
`;
            case "image5":
            case "Chimera":return img`
............................................
............................................
............................................
........................ffffffffffff........
.......................ffeecccceeeefff......
......................ffecccccccccceeff.....
.....ffff.............fcccccccc77777ecff....
...fffeeffff..........fffcccccce777777cff...
..ffeeeeeeefff.......ffccccccccff77777eeff..
..feceee44eeeff.....ffe5eccccceffeee777eef..
.ffecbb44444eef.....fee55ffffefffffe7777ef..
.fecb4dd44444cff....feeecffffff...ffc777ef..
.fecbdddd4444eef....feffff.........fce77eff.
.fecebb4d4444ecff...ffff...........fff777cf.
.fceece4d44444eefffff...............ff777ff.
.fcebb4dd44444eeccccfffffffff.......ff777ff.
.fcee4444444eeeeeeeefffffffeff......ff777ff.
.fceee444444eccccce4d444444ecff....fff777ff.
.fceee44444ecccccccbb444ddd44eff..ffec777ff.
.feeee4444eeccccccccceeb4dddd4effffff777eef.
.ffceee444ecccccccccccccceddd47efbbe7777eff.
..fecee444eccccccccccccccccc4b777ffc7777ef..
..ffeeeee444ccccccccccccccce4b777777777eef..
...ffece4444beeccccccccceebddb777777777eef..
....ffece444dddbbbbbbbbb4dddd477777777cbff..
.....ffeee444ddd444dddddddddd4bce777cffff...
......ffceee4dddbebbb4ddddd44bcbcffffff.....
.......fceeeeebdbceeebdddddeeecffffff.......
.......fceefecbdbebbbee44ddeeeebf...........
.......fceefeeeddebfffbe4ddeeeebff..........
......ffceefffcddebffffffddceeecbf..........
......ffeeecffeb44ff...ffddcceeeff..........
.....fffeeffffff4df...fffddcfceeff..........
....ffeeeeff.fed4df...febdebeeefbf..........
....fdfeeeff.ff444f...ffb4ebfeefff..........
....ffffffff..fffff....fffffffff............
.......fff................fff...............
............................................
............................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
