namespace SpriteKind {
    export const Frenemy = SpriteKind.create()
    export const SpriteAsset = SpriteKind.create()
}
/**
 * VERY IMPORTANT NOTE!! YOU CAN NAME THESE CHARACTERS WHATEVER YOU WANT. THE NAMES I GAVE ARE NOT LAW
 */
// A Chimera is a monster found in Greek Myths: Has a lion's body, a griffin's wings, and a scorpion's tail. Can poison foes, breathe fire, and fly. Usually an enemy.
//  
let Chimera = sprites.create(assets.image`Chimera`, SpriteKind.SpriteAsset)
// A metallic robot that can be a very powerful ally or a very deadly foe.
let Robot = sprites.create(img`
    ..................................
    ..................................
    .........fffff....................
    ........ffcccf....................
    ......fffe494fffff................
    ......fcce494ffccff...............
    ......fcce494ec4dcf...............
    .....ffc4e494ee4deff..............
    .....fc44e494ee4ddcf..............
    .....fc44eeee4e4ddcf..............
    .....fc4eee444e4dd4f..............
    .....fc4e4e4444e4d4f..............
    .....fc4e4b444444d4ff.............
    .....fc4e4644444444cff............
    .....fecee444f44eee4eff...........
    .....ffcee444444ec.e4ef...........
    .....fcefeee44eeec.ee4ff..........
    ....ffeeefeeee44ec.eedcff.........
    ...ffc4eefeeee44ec.eeddef.........
    ..ffc444cffce444ee.eeddef.........
    ..fc4444cffeceeeee.cdddef.........
    .ffe444eefffceecf..fddddf.........
    .ff4444eeffecccec..fdd64f.........
    .ffee44cfffceeeede.cdd64f.........
    .ffee4effffeeeebdee4ddddf.........
    .ffeecffffc4eeebdee44dddf.........
    .ffeeff.fee4eee4dce4e44ef.........
    .ffefff.fee4eeed4cece4eef.........
    .fffff.ffcee4edd4cffe4fff.........
    .ffff..fceee4bd4e4cfeeff..........
    ......ffeec4eddef4effff...........
    ......feecfffffffe4cff............
    .....ffceeef....fc4eef............
    .....fce4ecf....fed4ef............
    .....fce4ecff...fed4eff...........
    .....fce4eeef...fe4d4cf...........
    .....fce44eef...fe4d4cf...........
    .....fcee4eef...fe4d4ef...........
    .....fcee4eff...fc4d4ef...........
    .....fcee4ef....fc4dd4f...........
    .....fcccecf....fceeeef...........
    .....fffffff....fffffff...........
    ..................................
    ..................................
    ..................................
    ..................................
    ..................................
    `, SpriteKind.SpriteAsset)
// Fire manipulating wizard (enemy)
let Fire_Sorcerer = sprites.create(img`
    ..................1111.................
    .................11ee11................
    .............111.14444111..............
    .............1c11142221c1111...........
    ............11e21f4444feecf1...........
    ............1ee22ece44fceef1...........
    ............1e2222eccccceec1...........
    ..........111cebbeebe2eeeec1...........
    ..........1cceee22e2bbeeeec11.111......
    ...1111111122ecccebbe2ceccec111c1......
    ...1ccccccceeeccffeebb2efcee1cec111111.
    ..1122cee222ccfffffceeceffcceee1ee1ec1.
    .11e22cccec8fcffffffb22eff1cce1eceeee11
    112222222288ccffffe22ebcee111ceee44eef1
    1e2d111442cfcfffff22e2ccce11cee442244e1
    1edd444d1d22cfffff22ee2ccec1ee2ec..c4e1
    1e14...24132effff22beecccecce2..e..24e1
    1ed2cc.c.4ddeffffbe2eeccfcfe2c...ce44c1
    111422c..c41efffff22eeccff1e2ec2e224b11
    ..1144222221efffff2eeeccf111142224dc11.
    ...1cb44224dcfffffceecccf111d1dddb111..
    ...111c444c1ffffffceeccc1111ceecc11....
    .....11111111ffffceeccc11..1111111.....
    ......111...1111fceeec11...............
    ..............1f11eec11................
    ..............1111cee1.................
    ................11eec1.................
    ................1ceec1.................
    ................1fecc1.................
    ................11e111.................
    .................111...................
    `, SpriteKind.SpriteAsset)
// Skeleton Archer
// 
let SkellyMan_Archer = sprites.create(img`
    ..................
    ..................
    ..................
    ..................
    ..................
    ..................
    .......d111..e....
    .......df1f..9e...
    .......d111..9e...
    ........d1...9.e..
    .....d1ddddd.9.e..
    ....d1.d111.191e1.
    ....d1..d1..19111.
    ....d1.d111..9.e..
    ....d1..d1...9.e..
    .......d111..9e...
    .......d1d1..9e...
    .......d1d1..e....
    .......d1d1.......
    .......d1d1.......
    ..................
    ..................
    ..................
    ..................
    ..................
    ..................
    ..................
    ..................
    `, SpriteKind.SpriteAsset)
// Tiny robot gut. Think 3P0 from Star Wars. I do not want the player to be able to fight it or something. It should just be a character that walks randomly around the map and tells a joke or some information when you interact with it. Or You can do whatever you want.
let Mini_Robot = sprites.create(img`
    .........................
    .........................
    .........................
    ..........cbb............
    .........cbbbb...........
    .........cb9b9...........
    .........cb9b9.cb........
    .........cbbbb.69........
    ..........cbb..cb........
    .........ccbbb.cb........
    ......cbbbcb9bcbb........
    ......cb.ccb9b...........
    ......69.ccbbb...........
    ......cb.ccbbb...........
    ..........cbbb...........
    ..........cbcb...........
    ..........cbcb...........
    ..........cbcb...........
    ..........cbcb...........
    ..........cbcb...........
    ..........cbcb...........
    .........................
    .........................
    .........................
    .........................
    `, SpriteKind.SpriteAsset)
// Small dwarf barbarian/fighter
let Dwarf_warrior = sprites.create(img`
    . . . . . . . . . . . . . . . . . . 
    1 b . . . . . . . . . . . . b 1 . . 
    1 b b . . . . . . . . . . b b 1 . . 
    1 b b . . . c b b b b . . b b 1 . . 
    1 b b . . c c b b b b . . b b 1 . . 
    . . e . . c d f c b f . . e . . . . 
    . . e . . c d f c b f . . e . . . . 
    . . d d c c c 4 4 4 4 c d d . . . . 
    . . e . . c c 4 d d 4 . . e . . . . 
    . . e . . c c 4 4 4 4 . . e . . . . 
    . . . . . c b 4 4 4 b . . . . . . . 
    . . . . . c b 4 . c b . . . . . . . 
    . . . . . c b . . c b . . . . . . . 
    . . . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . . . 
    `, SpriteKind.SpriteAsset)
// Medival Knight dude
let Medival_knight_guy = sprites.create(img`
    .........................
    .........................
    ...................b.....
    ...........cbbb....b.....
    ..........ccbbbb...b.....
    ..........ccffff...b.....
    ..........ccbbfb...b.....
    ..........ccbbfb...b.....
    ..........cccbfb...b.....
    ......bb11cccccc...b.....
    ......bfc1ccbbbb...b.....
    ......bfc1ccbbbbc.ccc....
    ......bfc1ccbbbbcbbf.....
    ......bfc1ffffff...b.....
    ......bfc1bccccb.........
    ......bfc1bc..cb.........
    ......bfc1f....f.........
    ......bfc1b....b.........
    ......bfc1c....c.........
    ......bb11c....c.........
    .........................
    .........................
    .........................
    .........................
    .........................
    `, SpriteKind.Player)
